engines:
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false
    config:
      languages:
        python:
          mass_threshold: 75
  fixme:
    enabled: true
  radon:
    enabled: true
  markdownlint:
    enabled: true
  pep8:
    enabled: true
checks:
  file-lines:
    config:
      threshold: 500
  method-lines:
    config:
      threshold: 40
  argument-count:
    config:
      threshold: 20
ratings:
  paths:
    - "**.py"
    - "**.md"
exclude_paths:
  - tests/
  - docs/